### ISSUE TITLE
Maps look strange on who we are page

### ISSUE THREAD

**Issue by davidebukali** [devinit/DIwebsite-redesign#947] opened 2021-01-12 07:27 UTC
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[ x] Bug report 
</code></pre>

**Describe the Issue**
Map pixels are blurred https://devinit.org/who-we-are/?nav=header

**To Reproduce**
Replace the content below with the steps to reproduce the behaviour.
https://devinit.org/who-we-are/?nav=header

**Screenshots/GIF**
![map1](https://user-images.githubusercontent.com/1607276/104282737-911d4280-54c0-11eb-8a7d-2fad0d124dfb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Environment/Server:**
<pre><code>
- [x] Production
- [ ] Staging
- [ ] Development
</code></pre>

**Additional Context**

Requested Delivery Date: dd/MMM/YYYY

**Comment by edwinmp** [comment] 2021-01-12 07:43
Duplicate of #936 ... since 936 had a general title, there's no need to create a new issue... just move it back to ToDo. Also, it's already fixed on [Who we are](https://dev.devinit.org/who-we-are/?nav=header) ... just needs to be deployed

**Closed by edwinmp** 2021-01-12 07:43 UTC
