### ISSUE TITLE
Remove trailing comma from authors list on publications

### ISSUE THREAD

**Issue by edwinmp** [devinit/DIwebsite-redesign#236] opened 2019-09-27 12:00 UTC
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**
Can we remove the comma at the end after the name of the last person listed under Author(s)

**Screenshots/GIF**
![Bug on Pubs pages](https://user-images.githubusercontent.com/5672438/65767744-71310680-e137-11e9-84c8-df50ab55cae8.PNG)

**Comment by k8hughes** [comment] 2019-10-16 11:16
@edwinmp is this a duplicate of #235 ?

**Comment by edwinmp** [comment] 2019-10-16 13:24
Nope ... same screenshot, different issue.

**Closed** 2019-10-25 15:57 UTC
Labels: bug
