### ISSUE TITLE
Footnote function not working

### ISSUE THREAD

**Issue by alice-mcandrew-development-initatives** [devinit/DIwebsite-redesign#955] opened 2021-02-08 15:21 UTC
I noticed that the footnote function was not working for case study boxes when moderating this page: https://devinit.org/resources/aid-data-2019-2020-analysis-trends-before-during-covid/. The page needed to go live so I established a short-term work-around, linking the copying instead as a means of referencing external sources, but the issue persists. I'm not sure if this is a bug (which hasn't been spotted due to the circumstances not arising yet) or a regression (based on recent changes made to allow footnotes >5 to be hidden).

**[These screenshots were taken during moderation but the page was later amended (as noted)]**
For example, you can see here that, when the footnote number seven was added in the cms, the footnote reference pulled through onto the page:
![Screenshot (204)](https://user-images.githubusercontent.com/55877063/107239064-64593e00-6a20-11eb-822e-17ec8226251a.png)

However, the footnote did not link through to the footnotes section at the end of the page:
![Screenshot (205)](https://user-images.githubusercontent.com/55877063/107239092-6de2a600-6a20-11eb-8d2f-fcbef8a707d7.png)

(The footnote function was also temperamental (working in one instance but not in another) for footnotes that were within infographic captions but seemed fine in the WYSIWYG editor).

**Comment by alice-mcandrew-development-initatives** [comment] 2021-02-10 10:44
I'm now experiencing further problems with footnotes in uploading a long form publication: https://devinit.org/resources/supporting-longer-term-development-crises-nexus-lessons-somalia/executive-summary/

There are seven notes in the executive summary (marked up in the cms) but only five area appearing on the live page:
![image](https://user-images.githubusercontent.com/55877063/107499358-cafb6a80-6b8c-11eb-810c-2f265fa78e86.png)

(FYI, @GeorgeCarver)

**Comment by k8hughes** [comment] 2021-02-10 10:52
@edwinmp could you investigate, then assign to someone who has capacity to do it today?

**Comment by edwinmp** [comment] 2021-02-10 11:10
Hi @alice-mcandrew-development-initatives could you please give me a brief description of how footnotes are created cos I'm not sure the issue is with the recent changes since it's functioning just fine for the existing pages I can find https://devinit.org/resources/socioeconomic-impact-of-covid-19-in-uganda/#downloads

**Comment by edwinmp** [comment] 2021-02-10 11:22
@alice-mcandrew-development-initatives found the problem ... the code update to only show 5 footnotes was incomplete & the partial change resulted in this bug.

**Comment by alice-mcandrew-development-initatives** [comment] 2021-02-10 11:48
Yeah, it seems to just be affecting new pages set up since the 'Show more' function was added.

I've added an extra test footnote on this page for example: https://devinit.org/resources/supporting-longer-term-development-crises-nexus-lessons-somalia/executive-summary/

**Step 1: Select 'Footnote' in WYSIWYG EDITOR module**
![Screenshot (209)](https://user-images.githubusercontent.com/55877063/107505884-39442b00-6b95-11eb-8b3b-ca070ef014aa.png)

**Step 2: Insert footnote copy**
![Screenshot (210)](https://user-images.githubusercontent.com/55877063/107505897-3ea17580-6b95-11eb-9ed8-bbdf62163d2e.png)

So it appears in the cms
![Screenshot (211)](https://user-images.githubusercontent.com/55877063/107505935-47924700-6b95-11eb-8604-0157b750fb13.png)

**Step 3: Publish to view on webpage**

It appears within the body copy
![image](https://user-images.githubusercontent.com/55877063/107506028-6c86ba00-6b95-11eb-9974-a2a3fbdcbda4.png)

But not in the footnotes section at the bottom of the page
![image](https://user-images.githubusercontent.com/55877063/107506078-7dcfc680-6b95-11eb-88b7-d004414e7e89.png)

**Comment by akmiller01** [comment] 2021-02-10 13:33
More than 5 are coming in as class `extra hidden` @edwinmp maybe this plugin isn't functioning as intended? https://github.com/devinit/DIwebsite-redesign/blob/37219a254264bea9e4747cc127eaf9b4e3e10c57/src/plugins/footnotes.ts

**Comment by edwinmp** [comment] 2021-02-10 16:23
Hi @alice-mcandrew-development-initatives ... the fix for this has been deployed.

**Closed by edwinmp** 2021-02-10 16:23 UTC
Labels: priority, regression
