### ISSUE TITLE
Add chapter navigation to the Appendix template

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/DIwebsite-redesign#610] opened 2019-12-02 16:40 UTC
Want to add the chapter navigation to this template: http://development-initiatives.surge.sh/page-templates/14-2-publication-appendix

> Alice  @Anna presumably we also need a way to get back to the publication summary page from the appendixes? I don't think the template accounts had factored this functionality in: http://development-initiatives.surge.sh/page-templates/14-2-publication-appendix

**Comment by BenDarby** [comment] 2019-12-03 09:44
@BenDarby updated chapter navigation and added it to the above template

**Comment by benjamincoleman** [comment] 2019-12-09 10:18
@BenDarby we'll want to pull across the design changes we've just completed on the GNR chapter navigation to here.

**Comment by urlsangel** [comment] 2019-12-09 11:20
@akmiller01 @edwinmp 

Some notes on implementation changes compared to what's been done on GNR:

#### "View full report" link
It looks like you already have this in your `nav.html` template, so that should be fine.

- https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/chapter-nav/nav.html#L22
- https://github.com/devinit/gnr-website/blob/master/templates/reports/chapter-nav/nav.html#L20

#### List slice no longer required

The previous implementation sliced the list due to design constraints, this is no longer required, so the full list of items can be passed in the `nav-item.html` loop:

- https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/chapter-nav/nav.html#L25
- https://github.com/devinit/gnr-website/blob/master/templates/reports/chapter-nav/nav.html#L24

#### `data-has-sections` used as a selector for triggering in the JS

Wrap the `data-has-sections` attribute in a conditional, as this is used to determine whether to trigger the subnav or not.

- https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/chapter-nav/nav-item.html#L10
- https://github.com/devinit/gnr-website/blob/master/templates/reports/chapter-nav/nav-item.html#L8

#### Wrap the subnav in a conditional

As per the `data-has-sections`, wrap the subnav in a conditional so that this is only outputted when necessary (summaries don't have sub-sections in GNR).

- https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/templates/publications/chapter-nav/nav-item.html#L22
- https://github.com/devinit/gnr-website/blob/master/templates/reports/chapter-nav/nav-item.html#L18

**Comment by akmiller01** [comment] 2019-12-09 13:43
Done! https://github.com/devinit/DIwebsite-redesign/pull/638

**Comment by BenDarby** [comment] 2019-12-09 14:58
@urlsangel @benjamincoleman @akmiller01 I've added the updated chapter navigation from GNR to DI, it can be viewed on surge

**Comment by akmiller01** [comment] 2019-12-09 16:28
@urlsangel will this require an update to our pattern library JS as well? I've added the conditional for whether a chapter has sections or not, and this seems to not be operational. That's removed the "Read whole {{label}}" button in the grey section, and the section on the left is still toggling the subnav rather than navigating to the page:

![image](https://user-images.githubusercontent.com/2836840/70453517-e6de1a80-1a76-11ea-8bb7-76a5ccaa4c65.png)

E.g. Trying to navigate to the exec summary from a chapter page: http://178.128.102.213/publications/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/

**Comment by urlsangel** [comment] 2019-12-09 16:40
@akmiller01 

Yes, the changes above go in tandem with the JS update in the PL - I assumed this was being ported over by Ben.

@BenDarby - have you ported over the updated `chapterNav.js` from GNR to DI?

**Comment by akmiller01** [comment] 2019-12-09 16:41
Spotted it here. https://github.com/devinit/DIwebsite-redesign/tree/feature/pattern_library I'll need to merge that in as well. Cheers @urlsangel

**Comment by akmiller01** [comment] 2019-12-09 17:31
Just merged the new JS into develop @urlsangel I'm afraid it's still not working for me. Toggling back and forth between gnr-website and this repo and I'm having trouble spotting what I've done wrong: http://178.128.102.213/publications/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/ Still cannot click through to Exec summary.

**Comment by akmiller01** [comment] 2019-12-09 20:42
@urlsangel and @BenDarby  just confirmed that this isn't working via the pattern library. You can change the `href` of the "Executive Summary" anchor to something other than `#` and try clicking on it. It's still trying to open the side-nav, even though it has no sections:

![image](https://user-images.githubusercontent.com/2836840/70471052-6e895080-1a9a-11ea-856a-f02596822446.png)

**Comment by urlsangel** [comment] 2019-12-10 10:24
Hi @akmiller01 

The JS hadn't been ported across from GNR.

I've updated the `pattern_library` branch with working nav markup and JS - the nav is now working as expected in the PL, and should be good for you to implement into production. It should just be a matter of bringing the JS across.

Apologies for the confusion!

**Comment by akmiller01** [comment] 2019-12-10 13:38
Cheers @urlsangel tested and working now!

**Closed** 2019-12-12 15:30 UTC
Labels: Visual design
