### ISSUE TITLE
T1b General with Accounts module

### ISSUE THREAD

**Issue by k8hughes** [devinit/DIwebsite-redesign#39] opened 2019-06-12 09:59 UTC
Sketch: https://marvelapp.com/3j51290/screen/57215547

Design: http://development-initiatives.surge.sh/page-templates/01b-general-with-accounts-module

Functional Spec: 

This page is a variation of #19 

We have the standard hero here, with page title and hero content, plus the image with credit if required.

There's the sidebar menu on the right, which has had a recent update to the way the title is spelled out "More about:" being the thing that has changed. What should happen there is the "More about:" will be fixed and the "What we do" will be the top page of the section that has this menu. So, What we do, Who we are etc. etc.

Under the hero we have streamfield block from T1 #19 

Then we have a list of accounts groups. The design shows two groups, but there should be no limit to the number of groups. 

Each group has the following: 
- title
- introduction (paragraph + links)
- list of downloads. For each download we have
    - title
    - file downloads. Note this is the same content in different formats for accessibility reasons

---

This could just be text, and then it’s possible to 

a) grow over time  
b) be a nested tree map

I think that’s the best option given the anticipated low usage of this page.

---

@Darbice want to also include the filename for the download - so I've updated this in the sketch. This is true of anywhere we feature this download module.

![Screen_Shot_2019-05-29_at_15.40.51](https://gitlab.com/the-b-team/development-initiatives-website/uploads/f0b7f3e44cc3fb1eaaff648b91557b12/Screen_Shot_2019-05-29_at_15.40.51.png)

Review,Visual design,move-to-github

**Comment by k8hughes** [comment] 2019-09-25 10:12
I wanted to be able to add this page as it is described in the IA sitting as a child of "who we are" but the only child page allowed under  "who we are" is an "our story" page  which automatically incerpts a timeline.

@Napho what is hte name of the template in wagtail that I should be selecting?  Please can you allow it to be a child of "who we are"

**Comment by edwinmp** [comment] 2019-09-26 11:34
@k8hughes this should be supported under the existing General Page ... so I guess adding it as a child of all should solve this.

**Comment by k8hughes** [comment] 2019-10-11 09:19
http://178.128.102.213/who-we-are/our-funding2/ 

LGTM

**Comment by alice-mcandrew-development-initatives** [comment] 2019-10-15 14:48
@k8hughes I will test this when we have the content to upload for this page: http://159.65.56.142/who-we-are/our-finances/

**Comment by alice-mcandrew-development-initatives** [comment] 2019-10-25 13:38
@k8hughes I didn't add the content for this page originally but I've played around with it (since the fix) and can't get the end section to work as intended. Please can you advise on what we need to do to make this work.

What it looks like now:
![Our finances live](https://user-images.githubusercontent.com/55877063/67575643-e7278e00-f734-11e9-886f-37950dc0a4d0.JPG)

What it should look like:
![Our finances pattern](https://user-images.githubusercontent.com/55877063/67575650-ebec4200-f734-11e9-9590-35d42ff581a4.JPG)

**Comment by k8hughes** [comment] 2019-10-25 13:42
@edwinmp @davidebukali how do we make the PDF and Dox links go on different lines as per the designs?

**Comment by edwinmp** [comment] 2019-10-25 13:45
@k8hughes that's not the difference I'm seeing.

@alice-mcandrew-development-initatives should we remove the file names? Also, I see there's a weird issue with the backgrounds ... will look into it. Could be an FF issue.

**Comment by alice-mcandrew-development-initatives** [comment] 2019-10-25 14:09
@k8hughes 
I don't think the Dox files were added - I'll do this now

@edwinmp 
1) Yes please, just the file title, type and size as per pattern
2)  Thank you!

**Comment by alice-mcandrew-development-initatives** [comment] 2019-10-25 14:21
@k8hughes 
Apparently a docx version of these does not exist, so no need to worry about that

**Comment by edwinmp** [comment] 2019-11-12 08:02
> @edwinmp
> 
> 1. Yes please, just the file title, type and size as per pattern
> 2. Thank you!

Hi @alice-mcandrew-development-initatives a fix for this has been deployed

**Comment by alice-mcandrew-development-initatives** [comment] 2019-11-12 10:29
@edwinmp, when I look at the page, the background still appears differently to the pattern library for the last section.

What it looks like now: http://159.65.56.142/who-we-are/our-finances/

What it should look like:
![Capture](https://user-images.githubusercontent.com/55877063/68663723-17459e00-0537-11ea-9543-0c18b9b833d3.JPG)

**Comment by edwinmp** [comment] 2019-11-12 10:34
@alice-mcandrew-development-initatives use the `alt` checkbox to set the background to white or grey...
 
![image](https://user-images.githubusercontent.com/5672438/68664204-06a22180-0551-11ea-931f-c1041adbc7d6.png)

**Comment by alice-mcandrew-development-initatives** [comment] 2019-11-12 10:36
@edwinmp Ah, sorry!

**Comment by alice-mcandrew-development-initatives** [comment] 2019-11-14 12:13
How difficult would it be to add a hyperlink to the 'Section sub heading' here:
![image](https://user-images.githubusercontent.com/55877063/68856278-0718f480-06d8-11ea-9840-e9afdc2cbb32.png) 
We may need to change content if it's a problem.

**Comment by k8hughes** [comment] 2019-11-15 09:39
@edwinmp what are your thoughts?

**Comment by edwinmp** [comment] 2019-11-15 10:45
@alice-mcandrew-development-initatives I'll make it RichText

**Comment by akmiller01** [comment] 2019-11-18 18:10
Did this ever make it into a fix/misc @edwinmp ?

**Comment by edwinmp** [comment] 2019-11-19 09:06
Yes it did @akmiller01

**Comment by k8hughes** [comment] 2019-11-25 10:05
@alice-mcandrew-development-initatives can you check over this and close if you are happy with the implementation?

**Closed** 2019-11-25 11:38 UTC
