### ISSUE TITLE
Pop-up menu doesn't function correctly on mobile device 

### ISSUE THREAD

**Issue by SimonMurphyDI** [devinit/DIwebsite-redesign#863] opened 2020-07-21 21:52 UTC
## I'm submitting a ...
Check one of the following options with "x" and add the appropriate label to the issue as well
<pre><code>
[x] Bug report 
[ ] Regression (behaviour that used to work and stopped working in a new release)
</code></pre>

**Describe the Issue**

When you use the pop up menu on a mobile device and click on 'read whole chapter', the menu button seems to disappear: it's actually hidden: you have to zoom out to see it - see the attached screengrab   
![Screenshot_20200721-224756](https://user-images.githubusercontent.com/22001094/88110615-6652d100-cba4-11ea-8db4-fd1c85463506.png)

**To Reproduce**

Access the page on a mobile, click on the pop up menu, choose to view a whole chapter

**Expected Behaviour**

Menu to remain visible and accessible in the bottom right hand corner. 

**Smartphone (please complete the following information):**
 - Device: iPhone X - Chrome simulator

Requested Delivery Date:

As soon as possible please - users can't return to the report parent page without this, so they'll get stuck in chapters

**Comment by edwinmp** [comment] 2020-07-22 02:08
@benjamincoleman could you please help troubleshoot this ... the markup looks fine, but this breaks on small devices for the live site yet works on the PL.

**Comment by benjamincoleman** [comment] 2020-07-23 11:32
Ok, this is an odd one. 

The cause is a URL link the footnotes - number 7 on this page: https://devinit.org/resources/global-humanitarian-assistance-report-2020/people-and-crisis/

This forces the page to be wider, so the fixed position of the chapter navigation appears off screen. There's nothing wrong with it though - it's the link not wrapping that is the issue. You can see the link below:

![Screenshot 2020-07-23 at 12 27 30](https://user-images.githubusercontent.com/64877/88281739-1711bb00-cce0-11ea-8dc6-6db990b5e85a.png)

Oddly, this doesn't happen on my Google Pixel 4 phone: 

![Screenshot_20200723-122933](https://user-images.githubusercontent.com/64877/88281845-49bbb380-cce0-11ea-9308-badf3749e418.png)

So, @BenDarby can you check we have something to deal with links not wrapping in the footnotes please?

**Comment by BenDarby** [comment] 2020-07-24 09:42
@edwinmp @benjamincoleman the CSS implemented to force links to wrap was attached to a class called `footnotes__link` so instead I have applied the CSS to the `<a>` in `footnotes__text` this should fix the issue above. Pushed to the `pattern_library` feature branch

**Comment by edwinmp** [comment] 2020-07-28 16:10
@SimonMurphyDI this is fixed on staging
http://staging.devinit.org/resources/global-humanitarian-assistance-report-2019/chapter-1-people-crisis-and-assistance/#section-1-2

**Comment by alice-mcandrew-development-initatives** [comment] 2020-07-29 15:47
@edwinmp This looks good to me on staging (but worth noting I'm on Chrome through an Android phone rather than iPhone and don't have access to an iPhone in my household so if someone needs to check on a different device perhaps worth waiting for @SimonMurphyDI or someone else in the Comms team to check)

**Closed** 2020-08-05 04:50 UTC
Labels: bug
